package network_test

import (
	"testing"

	"github.com/itunified-io/dbx/pkg/host/network"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseIPRoute(t *testing.T) {
	output := `default via 10.10.0.1 dev eth0 proto dhcp metric 100
10.10.0.0/24 dev eth0 proto kernel scope link src 10.10.0.50 metric 100
10.20.0.0/24 via 10.10.0.1 dev eth0
`
	routes, err := network.ParseIPRoute(output)
	require.NoError(t, err)
	assert.Len(t, routes, 3)
	assert.Equal(t, "default", routes[0].Destination)
	assert.Equal(t, "10.10.0.1", routes[0].Gateway)
}

func TestParseResolvConf(t *testing.T) {
	content := `# Generated by NetworkManager
nameserver 10.10.0.1
nameserver 1.1.1.1
search itunified.local
`
	dns, err := network.ParseResolvConf(content)
	require.NoError(t, err)
	assert.Equal(t, []string{"10.10.0.1", "1.1.1.1"}, dns.Nameservers)
	assert.Equal(t, []string{"itunified.local"}, dns.SearchDomains)
}

func TestParseChronyTracking(t *testing.T) {
	output := `Reference ID    : A29FC801 (ntp.ubuntu.com)
Stratum         : 2
Ref time (UTC)  : Thu Apr 10 12:00:00 2026
System time     : 0.000012345 seconds fast of NTP time
Last offset     : +0.000001234 seconds
RMS offset      : 0.000015000 seconds
Leap status     : Normal
`
	ntp, err := network.ParseChronyTracking(output)
	require.NoError(t, err)
	assert.Equal(t, "ntp.ubuntu.com", ntp.Server)
	assert.Equal(t, 2, ntp.Stratum)
	assert.Equal(t, "Normal", ntp.LeapStatus)
	assert.InDelta(t, 0.000012345, ntp.OffsetSec, 0.0001)
}
